spring:
  profiles.active: prod
  application:
    name: catalog-service
  config.import: "optional:configserver:http://localhost:8888"
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 20
      pool-name: polardb-catalog-pool
  jpa:
    hibernate.ddl-auto: validate

server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    threads:
      max: 100
      min-spare: 10

polar:
  greeting: Welcome to Tom's book catalog!

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE